AlarmRegistrationSystem/Components/MenuViewComponent.cs
using AlarmRegistrationSystem.Infrastructure;
using AlarmRegistrationSystem.Models;
using AlarmRegistrationSystem.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace AlarmRegistrationSystem.Components
{
    public class MenuViewComponent :ViewComponent
    {
        private UserManager<AppUser> userManager;
        private readonly IHostingEnvironment _hostingEnvironment;
        private List<Dictionary<string, string>> links;
        private readonly IStringLocalizer<SharedResources> localizer;

        public MenuViewComponent(UserManager<AppUser> userManager, IHostingEnvironment hostingEnvironment, IStringLocalizer<SharedResources> localizer)
        {
            _hostingEnvironment = hostingEnvironment;
            this.userManager = userManager;
            this.localizer = localizer;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            AppUser user = await userManager.FindByNameAsync(User.Identity.Name);
            var roles = await userManager.GetRolesAsync(user);
            string role = roles[0];
            string path = _hostingEnvironment.ContentRootPath + "\\Infrastructure\\JsonData\\" + role + "Links.json";
            links = JsonDataReader.ReadJson<List<Dictionary<string,string>>>(path);
            foreach (var link in links)
            {
                string key = link["linkTitle"];
                link["linkTitle"] = localizer[key];
            }
            MenuViewModel model = new MenuViewModel
            {
                Links = links,
                FirstName = user.FirstName,
                SecondName = user.SecondName,
                Email = user.Email,
                UserName = user.UserName
            };

            return View(model);
        }
    };
}

AlarmRegistrationSystem/Views/Shared/Message.cshtml
@if (TempData["Message"] != null)
{
    <script type="text/javascript">
           M.toast({ html: "@TempData["Message"]", classes: "teal darken-3", displayLength: 2500 });
    </script>
}

AlarmRegistrationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/materialize/dist/css/materialize.css" />
    <link rel="stylesheet" href="~/lib/Font-Awesome/css/all.css" />
    <link rel="stylesheet" href="~/Style.css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    @RenderSection("styles", false)
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="row col s12 card-panel teal lighten-2 valign-wrapper" style="padding:0.50rem;">
        <div class="col s2">
            <a href="#" data-target="slide-out" id="menuIcon" class="sidenav-trigger">
                <i class="fas fa-bars fa-2x black-text"></i>
            </a>
        </div>
        <div class="col s6 white-text offset-s1 offset-m4 offset-l2">
            <h5 class="hide-on-med-and-down no-margin valign-wrapper">
                <a href="/home/index" class="white-text valign-wrapper">
                    <img src="~/android-chrome-192x192.png" style="width:3rem;" />
                    <span>Alarm Registration System</span>
                </a>
            </h5>
            <h5 class="hide-on-large-only no-margin valign-wrapper">
                <a href="/home/index" class="white-text valign-wrapper">
                    <img src="~/android-chrome-192x192.png" style="width:3rem;" />
                    <span>ARS</span>
                </a>
            </h5>
        </div>

        <div class="input-field col l3 m5 no-margin selectwhite">
                <select id="language" class="red">
                    <option id="culturepl" value="pl">Polish (Polski)</option>
                    <option id="cultureen" value="en">English (English)</option>
                </select>
        </div>

    </div>
    <div class="row">

        <ul id="slide-out" class="sidenav">
            @await Component.InvokeAsync("Menu")
            <li><a asp-action="Logout" asp-controller="Account"><i class="fas fa-power-off prefix"></i>@Localizer["logout"]</a></li>
        </ul>

        <div class="col s12 center-align section">
            <div id="container" style="margin-top:4rem;">
                @RenderBody()
            </div>
            <div class="footer-copyright section">
                <div class="row col s12">
                    <h6>&copy 2019-2020 Alarm Registration System, All rights reserved.</h6>
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
    <script src="~/lib/materialize/dist/js/materialize.js" type="text/javascript"></script>
    <script src="~/Scripts.js" type="text/javascript"></script>
    <script src="~/lib/signalr/dist/browser/signalr.js" type="text/javascript"></script>
    <script>
        InitSignalR();
        $(document).ready(function () {
            $('.sidenav').sidenav();
            $("#language").change(function () {
                let culture = $(this).val();
                ChangeLanguage(culture);
            });

            var url = "/system/GetCulture";
            var func = function (response) {
                $("#culture" + response).attr("selected", "selected");
                $("select").formSelect();
            }
            AjaxAndFunc(url, func, null);
        });
        var text = '@TempData["Error"]';
        if (text !== '') {
            M.toast({ html: text, classes: "amber darken-1 special", displayLength: 2500 });
        }
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>